// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Escape.iOS
{
	public partial class MainController : UIViewController
	{
		public MainController (IntPtr handle) : base (handle)
		{
		}

        public const string IDENTIFIER = "MainController";

        private int _count = 1;

        partial void btnHello_Click(NSObject sender)
        {
            _count++;

            string title = string.Format("{0} clicks!", _count);
            btnHello.SetTitle(title, UIControlState.Normal);
        }
	}
}
